### ISSUE TITLE
cuda runtime error (59) : device-side assert triggered during training

### ISSUE THREAD

**Issue by sonalinayak** [rohithreddy024/Text-Summarizer-Pytorch#3]
Hello!

I've been trying to use your code for training on Gigaword dataset, but after some iterations it starts to throw quite non-descriptive error: `cuda runtime error (59) : device-side assert triggered`.

Following suggestion from https://discuss.pytorch.org/t/runtimeerror-cuda-runtime-error-59/750/3 and setting `CUDA_LAUNCH_BLOCKING=1`, the backtrace of the error shows it happening in this line: https://github.com/rohithreddy024/Text-Summarizer-Pytorch/blob/master/train.py#L89 .

The training is done in [Colab](https://colab.research.google.com) with GPU support. I am using default config (as in the code on GitHub). The moment when the error happens seems to be rather undetermined - first time happened around 45000 iteration, but went past that after few retries, but now it happens always after 55000 iteration.

Have you seen an error like this? Do you know what can cause it?

I've tried to use PDB but after first CUDA error happens, calling any of the decoder-produced variables causes it as well. Do you know of any other ways that would help with debugging it?

Thank you!

**Comment by rohithreddy024** [comment]
I encountered this kind of error (abruptly getting cuda runtime error after some iterations) before, and in my case it happened due to backpropogation of gradients through non-differentiable functions. The decoder uses token generated in the previous time step as input in the current time step. So, we sample(non differentiable operation) token from the predicted word distribution at time step t-1 and use it as input at time step t . I encountered this error inside [train_batch_RL() function](https://github.com/rohithreddy024/Text-Summarizer-Pytorch/blob/master/train.py#L97) and solved it by adding [detach() to input token](https://github.com/rohithreddy024/Text-Summarizer-Pytorch/blob/master/train.py#L131). I also added detach() in [line 90](https://github.com/rohithreddy024/Text-Summarizer-Pytorch/blob/master/train.py#L90) just to be safe and didn't encounter any error thereafter.

So to solve your issue, try replacing [line 89](https://github.com/rohithreddy024/Text-Summarizer-Pytorch/blob/master/train.py#L89) with `is_oov = (x_t.detach() >= config.vocab_size).detach().long()`.

Otherwise try running the code using Pytorch 0.4.1 and cuda 9.0 which I used for my experiments. Hope this solves your issue.

**Comment by rohithreddy024** [comment]
Closing this issue. Please reopen if you still have the problem..

**Comment by sonalinayak** [comment]
Thank you so much for your advice. I believe the problem was with using google colab(probably was just running out of memory). So I tried using other GPU (with sufficient memory) and there was no error like this.

**Comment by rohithreddy024** [comment]
That's strange. If out of memory is the case, I think cuda will throw `RuntimeError: CUDA error: out of memory` instead of `RuntimeError: cuda runtime error (59) : device-side assert triggered at ...`. Anyway, consider my suggestion if error is raised again.

**Comment by sayan3710** [comment]
I changed the codes in line89 and lowered the version of torch in colab to 0.4.1 but even then i got the following error.
![error](https://user-images.githubusercontent.com/50476646/69596957-61685e00-0fd2-11ea-881a-57729610cab3.PNG)
![error2](https://user-images.githubusercontent.com/50476646/69596974-65947b80-0fd2-11ea-8b19-a82b32692860.PNG)
